# -*- coding: utf-8 -*-
"""Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBUh_t1meZerk4WO_AiGn9b_O3AUJB8w

## Financial Fraud Risk Analytics

---
"""

!pip install kagglehub

import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from kagglehub import KaggleDatasetAdapter

file_path = "Fraud Detection Dataset.csv"
df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,"ranjitmandal/fraud-detection-dataset-csv",file_path,)

df.head()

df.info()

df.isna().sum()

"""Insight: Dataset has missing data, we shall impute the dataset.

### Imputation of Missing Data
"""

df_for_pivot = df.copy()

#Trasaction is imputed with the mean amount. Mean gives us a good idea of the average amount in the trasaction.
trasaction_mean = df['Transaction_Amount'].mean()
df['Transaction_Amount'] = df['Transaction_Amount'].fillna(trasaction_mean)


#Transaction time has 2552 missing values; We shall use the mode to impute as it gives a rough idea about at which time we have the most trasactions.
trasaction_time_mode = df['Time_of_Transaction'].mode()[0]
df['Time_of_Transaction'] = df['Time_of_Transaction'].fillna(trasaction_time_mode)

#Device_Used will be an essential feature in the analysis, we shall fill it with the most frequent occurance(Mode).
device_used_mode = df['Device_Used'].mode()[0]
df['Device_Used'] = df['Device_Used'].fillna(device_used_mode)

#Location and Payment method are also essential, but adding mode to this would not help our analysis, it would skew the results towards the mode, hence fill with "Unknown"
df['Location'] = df['Location'].fillna('Unknown')
df['Payment_Method'] = df['Payment_Method'].fillna("Unknown")

df.isna().sum()

"""All missing data is imputed with it's specific strategy. We shall begin our EDA

### EDA
"""

df.info()

"""1. Are fraud transactions associated with higher or lower transaction amounts?"""

import matplotlib.pyplot as plt

df['log_amount'] = np.log1p(df['Transaction_Amount'])
fraud_df = df[df['Fraudulent'] == 1]

plt.figure(figsize=(20, 12))
plt.hist(fraud_df['log_amount'], bins=50, color='purple', edgecolor='black')

plt.title("Distribution of Fraudulent Transaction Amounts")
plt.xlabel("Log - Transaction Amount")
plt.ylabel("Frequency")
plt.grid(axis='y', alpha=0.3)
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(18, 8))
fig.suptitle('Total vs Fraudulent Transaction Distributions (Log Scale)', fontsize=16)


axes[0].hist(df['log_amount'], bins=50, color='blue', edgecolor='black', alpha=0.7)
axes[0].set_title('All Transactions')
axes[0].set_xlabel('Log Amount')
axes[0].set_ylabel('Frequency')

axes[1].hist(fraud_df['log_amount'], bins=50, color='red', edgecolor='black', alpha=0.7)
axes[1].set_title('Fraudulent Transactions Only')
axes[1].set_xlabel('Log Amount')
axes[1].set_ylabel('Frequency')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""The log-scaled transaction amount distribution reveals that fraudulent transactions occur within a relatively narrow range of transaction sizes. Unlike the overall transaction distribution, which includes extreme high-value transactions, fraud cases rarely appear at these extremes. Instead, fraudulent transactions cluster around the mid-range of typical transaction values, suggesting that fraudsters may intentionally mimic normal spending behavior to avoid detection.

2. Do frauds occur more frequently at specific time periods?
"""

import matplotlib.pyplot as plt


transactions_by_hour = df.groupby('Time_of_Transaction')['Fraudulent'].count()
fraud_by_hour = fraud_df.groupby('Time_of_Transaction')['Fraudulent'].count()

fraud_rate = (fraud_by_hour/transactions_by_hour)*100

plt.figure(figsize=(12, 6))
fraud_rate.plot(kind='line', color='crimson')

plt.title("Fraud Risk Rate by Hour of Day", fontsize=14)
plt.ylabel("Fraud Rate (Percentage)")
plt.xlabel("Hour (24-hour format)")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Insight: Analysis of fraud risk rates by hour shows that fraudulent activity is distributed throughout the day with only minor fluctuations. While small peaks appear in the afternoon and late evening, the overall fraud probability remains relatively stable across time, indicating that fraud detection systems must maintain consistent monitoring rather than relying solely on time-based patterns.

3. Do frauds occur more on specific devices and method of payment?
"""

df_for_pivot.dropna()
pivot = pd.pivot_table(df_for_pivot,values="Fraudulent",index="Payment_Method",columns="Device_Used",aggfunc="mean")

sns.heatmap(pivot, annot=True, cmap="Reds")

"""Insight: Fraud risk varies significantly depending on the combination of payment method and device type. Transactions conducted from unknown devices exhibit the highest fraud rates across several payment channels, highlighting the importance of device authentication and behavioral monitoring in fraud prevention systems.

4. Does transaction velocity (number of transactions in the last 24 hours) influence the likelihood of fraud?
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))


sns.boxplot(x='Fraudulent', y='Number_of_Transactions_Last_24H', data=df, palette='magma')

plt.title('Transaction Velocity: Normal vs. Fraudulent')
plt.xlabel('Is Fraudulent? (0 = No, 1 = Yes)')
plt.ylabel('Transactions in Last 24 Hours')
plt.grid(axis='y', alpha=0.3)
plt.show()

"""Interpretation: Analysis of transaction velocity indicates that fraudulent and legitimate transactions occur at similar activity levels within a 24-hour window. This suggests that transaction frequency alone is insufficient for identifying fraud, highlighting the importance of multi-factor fraud detection models that incorporate device behavior, payment methods, and user history.

5. Does previous fraud history increase fraud likelihood?
"""

plt.figure(figsize=(10, 6))
sns.barplot(x='Previous_Fraudulent_Transactions', y='Fraudulent', data=df, palette='coolwarm')
plt.title('Likelyhood of Fraud based on Historical Fraud')
plt.xlabel('Number of Ocurrances of Fraud(Historical)')
plt.ylabel('Likelyhood (In decimals)')
plt.grid(axis='y', alpha=0.3)
plt.show()

"""Insight: The analysis reveals that accounts with prior fraudulent transactions tend to exhibit higher fraud probabilities. This pattern suggests that fraud risk is not entirely random but may persist over time for certain accounts, highlighting the importance of incorporating historical fraud behavior into fraud detection systems.

6. Are newer accounts more vulnerable to fraud?
"""

df.info()

plt.figure(figsize=(10, 6))
sns.barplot(x='Fraudulent', y='Account_Age', data=df, palette='rocket')
plt.title('Account Age V/S Fraud Occurance')
plt.xlabel('Is Fraudulent? (0 = No, 1 = Yes)')
plt.ylabel('Account Age (IN DAYS)')
plt.grid(axis='y', alpha=0.3)
plt.show()

"""Insight: Analysis of account age indicates that fraudulent and legitimate transactions occur across accounts of similar age ranges. The small difference between the two groups suggests that account age alone does not strongly influence fraud probability. This pattern may indicate that fraud frequently occurs through account compromise rather than exclusively targeting newly created accounts.

7. Which combination of behavioral factors creates the highest fraud risk profile?
"""

df.info()

df_method_device = df.groupby(["Payment_Method","Device_Used"])["Fraudulent"].mean()

df_method_device = df_method_device.unstack()

sns.heatmap(df_method_device, annot=True)

df_payment_transactiontype = df.groupby(["Payment_Method","Transaction_Type"])["Fraudulent"].mean()
df_payment_transactiontype = df_payment_transactiontype.unstack()

sns.heatmap(df_payment_transactiontype, annot=True)

df_device_transactiontype = df.groupby(["Device_Used","Transaction_Type"])["Fraudulent"].mean()
df_device_transactiontype = df_device_transactiontype.unstack()

sns.heatmap(df_device_transactiontype, annot=True)

"""Risk Profile by HEATMAPS:

Device Conditions:
1.   Unknown devices
2.   Mobile devices in digital channels

Transaction Type
1.   Online purchases
2.   Bill payments

Payment Context:
1.   Net banking or UPI
2.   Unknown payment configurations

Insight: Fraud risk in the dataset is most strongly associated with abnormal device usage and digital transaction channels. Transactions originating from unknown devices particularly during online purchases exhibit the highest fraud probabilities. Fraud also appears more frequently in mobile-based digital transactions such as bill payments and online purchases. In contrast, traditional transaction channels such as ATM withdrawals and point-of-sale payments demonstrate lower fraud risk. These findings suggest that fraud detection systems should prioritize monitoring of device anomalies and online transaction behavior.
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import kagglehub
# import os
# 
# st.set_page_config(page_title="Fraud Detection Dashboard", layout="wide")
# 
# st.title("Fraud Detection Analytics Dashboard")
# 
# # Load dataset from KaggleHub
# @st.cache_data
# def load_data():
#     path = kagglehub.dataset_download("ranjitmandal/fraud-detection-dataset-csv")
# 
#     # Find CSV file in the downloaded dataset
#     csv_file = [f for f in os.listdir(path) if f.endswith(".csv")][0]
# 
#     df = pd.read_csv(os.path.join(path, csv_file))
#     return df
# 
# df = load_data()
# 
# # KPI Metrics
# total_transactions = len(df)
# fraud_transactions = df["Fraudulent"].sum()
# fraud_rate = fraud_transactions / total_transactions
# 
# col1, col2, col3 = st.columns(3)
# 
# col1.metric("Total Transactions", total_transactions)
# col2.metric("Fraud Transactions", fraud_transactions)
# col3.metric("Fraud Rate", f"{fraud_rate:.2%}")
# 
# st.markdown("---")
# 
# # Fraud Distribution
# st.subheader("Fraud vs Normal Transactions")
# 
# fig, ax = plt.subplots()
# sns.countplot(x="Fraudulent", data=df, ax=ax)
# st.pyplot(fig)
# 
# st.markdown("---")
# 
# # Transaction Amount Distribution
# st.subheader("Transaction Amount Distribution")
# 
# fig, ax = plt.subplots()
# 
# sns.histplot(df["Transaction_Amount"], bins=50, ax=ax)
# st.pyplot(fig)
# 
# st.markdown("---")
# 
# # Device vs Transaction Type Heatmap
# st.subheader("Device vs Transaction Type Fraud Risk")
# 
# pivot = pd.pivot_table(
#     df,
#     values="Fraudulent",
#     index="Device_Used",
#     columns="Transaction_Type",
#     aggfunc="mean"
# )
# 
# fig, ax = plt.subplots(figsize=(8,5))
# sns.heatmap(pivot, annot=True, cmap="Reds", ax=ax)
# st.pyplot(fig)
# 
# st.markdown("---")
# 
# st.subheader("Fraud Risk Profile")
# 
# st.write("""
# Typical Fraud Scenario:
# - Transaction from **Unknown Device**
# - **Online Purchase**
# - Digital payment channel
# - User with prior fraud history
# """)

!streamlit run app.py &>/dev/null &

from pyngrok import ngrok
ngrok.set_auth_token('ADD YOUR AUTHCODE')
public_url = ngrok.connect(8501)
public_url

